### ISSUE TITLE
Add feature to use pushed repo in cloud build api via Update build target details PUT

### ISSUE THREAD

**Issue by andrewatboom** [ElmarJ/unity-cloud-build-action#98]
I setup your action successfully in our repository and it works very well for the Master branch. However, the action does not update the cloud build with the branch that was pushed when it builds. So even though all the branches are triggering the builds the only code that's being built against is the master branch.

So either I have misconfigured something, WHICH IS VERY POSSIBLE, or we need to add a step in the JS files to do a put to the API updating the branch on the cloud build before launching the cloud build.

[Update build target details](https://build-api.cloud.unity3d.com/docs/1.0.0/index.html#operation--orgs--orgid--projects--projectid--buildtargets--buildtargetid--put)

I don't even see this endpoint used in the index.js file but I might be looking in the wrong place.

Thank you for writing this action it's making our life a lot easier.

**Comment by andrewatboom** [comment]
`name: 'Unity Cloud Build'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
     - '**'
  push:
    paths:
     - '**'
     - '.github/workflows/**'
    branches:
      # - master
      - '**'

jobs:
  cloud-build: # make sure the action works on a clean machine without building
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - ios # Build an iOS player.
          # - Android # Build an Android player.
          # - WebGL # WebGL.
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print Branch Name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}
      
      - name: Update Unity Cloud Build Branch with ${{ steps.extract_branch.outputs.branch }}
        uses: satak/webrequest-action@master
        with:
          url: 'https://build-api.cloud.unity3d.com/api/v1/orgs/${{ secrets.UNITY_ORG_ID }}/projects/${{ secrets.UNITY_PROJECT_ID }}/buildtargets/${{ matrix.targetPlatform }}'
          method: 'PUT'
          headers: '{"Authorization": "Basic ${{ secrets.UNITY_API_KEY }}"}'
          payload: '{ "settings": { "scm": { "type": "oauth", "branch": "${{ steps.extract_branch.outputs.branch }}" } } }'

      - name: Launch Unity Cloud Build For ${{ steps.extract_branch.outputs.branch }}
        uses: elmarj/unity-cloud-build-action@main
        with:
          orgid: ${{ secrets.UNITY_ORG_ID }}
          projectid: ${{ secrets.UNITY_PROJECT_ID }}
          buildtargetid: ${{ matrix.targetPlatform }}
          apikey: ${{ secrets.UNITY_API_KEY }}
          useactioncommit: true`

**Comment by andrewatboom** [comment]
I as able to work around this issue making a direct API call... here is my workflow.

```
name: 'Unity Cloud Build'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
     - '**'
  push:
    paths:
     - '**'
     - '.github/workflows/**'
    branches:
      # - master
      - '**'

jobs:
  cloud-build: # make sure the action works on a clean machine without building
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - ios # Build an iOS player.
          # - Android # Build an Android player.
          # - WebGL # WebGL.
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print Branch Name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}
      
      - name: Update Unity Cloud Build Branch with ${{ steps.extract_branch.outputs.branch }}
        uses: satak/webrequest-action@master
        with:
          url: 'https://build-api.cloud.unity3d.com/api/v1/orgs/${{ secrets.UNITY_ORG_ID }}/projects/${{ secrets.UNITY_PROJECT_ID }}/buildtargets/${{ matrix.targetPlatform }}'
          method: 'PUT'
          headers: '{"Authorization": "Basic ${{ secrets.UNITY_API_KEY }}"}'
          payload: '{ "settings": { "scm": { "type": "oauth", "branch": "${{ steps.extract_branch.outputs.branch }}" } } }'

      - name: Launch Unity Cloud Build For ${{ steps.extract_branch.outputs.branch }}
        uses: elmarj/unity-cloud-build-action@main
        with:
          orgid: ${{ secrets.UNITY_ORG_ID }}
          projectid: ${{ secrets.UNITY_PROJECT_ID }}
          buildtargetid: ${{ matrix.targetPlatform }}
          apikey: ${{ secrets.UNITY_API_KEY }}
          useactioncommit: true
```
